version: "3.9"
services:
  postgres:
    container_name: sqlboiler-postgres
    image: postgres:latest
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    # command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  # postgresql: declare a named volume to persist DB data
  pgvolume:
    driver: local
