output = "models/dm"
pkgname = "dm"
wipe     = true
no-tests = true
add-enum-types = true
add-soft-deletes = true
struct-tag-casing = "camel"
blacklist = ["migrations", "schema_migrations"]

[psql]
dbname = "sqlboiler-erg"
host   = "localhost"
port   = 5432
user   = "root"
pass   = "root"
sslmode = "disable"

[erg]
output = "models/erg"
output-ts = "models/models.ts"
pkgname = "erg"
wipe    = true
inline = false
blacklist = ["*.password", "*.token", "*.*hash", "schema_migrations"]